repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.83.6
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=INOUT.md
        - --hook-config=--add-to-existing-file=true
        - --hook-config=--create-file-if-not-exist=true
